mul=read.csv(choose.files())
View(mul)
summary(mul)
colnames(mul)=c("send" , "admin" , "marketing" , "state" , "profit")
View(mul)
attach(mul)
library(psych)
pairs(mul)
pairs.panels(mul)
cor(mul)
moddel=lm(profit~send+admin+marketing+state , data = mul)
summary(moddel)
modde=lm(profit~send  , data = mul)
summary(modde)
modde=lm(profit~admin, data = mul)
summary(modde)#significance data
modde=lm(profit~marketing , data = mul)
summary(modde)
modde=lm(profit~state , data = mul)
summary(modde)
cor(mul)
library(corpcor)
cor2pcor(cor(mul))
library(car)
plot(moddel)
influenceIndexPlot(moddel)
influencePlot(moddel)
library(MASS)
stepAIC(moddel)
moddel1=lm(profit~send+marketing , data = mul[c(-50),])
summary(moddel1)
vif(moddel)
moddel1=lm(profit~send+marketing , data = mul[c(-50),])
summary(moddel1)
pred=predict(moddel1,interval = "predict")
pred
vif(moddel1)
