sal=read.csv(choose.files())
View(sal)
summary(sal)
colnames(sal)=c("exp", "sal")
View(sal)
attach(sal)
library("lattice")
dotplot(sal$exp, main="Dot Plot of Waist Circumferences")
dotplot(sal$sal, main="Dot Plot of Adipose Tissue Areas")
range(sal)
boxplot(sal$exp,col="dodgerblue4")
boxplot(sal$sal,col="red", horizontal = T)
hist(sal$exp)
hist(sal$sal)
qqnorm(sal$exp)
qqline(sal$sal)
qqnorm(sal$exp)
qqline(sal$sal)
plot(sal$exp,sal$sal,main="Scatter Plot", col="Dodgerblue4", 
     col.main="Dodgerblue4", col.lab="green", pch=22)  

reg=lm(sal~exp ,data = sal)
summary(reg)
confint(reg,level = 0.95)
pred=predict(reg,interval = "predict")
pred
reg=lm(sqrt(sal)~exp , data = sal)
summary(reg)
reg=lm(log(sal)~exp, data = sal)
summary(reg)
reg<-lm(log(sal)~exp + I(exp*exp), data=sal)
summary(reg)
final_reg=lm(sal~exp ,data = sal)
summary(reg)
confint(reg,level = 0.95)
pred=predict(reg,interval = "predict")
pred
