toy=readxl::read_excel(choose.files())
View(toy)
summary(toy)
attach(toy)
plot(toy)
library(psych)
pairs(toy)
pairs.panels(toy)
cor(toy)
model_toy=lm(Price~Age_08_04+KM+HP+cc+Doors+Gears+Quarterly_Tax+Weight , data = toy)
summary(model_toy)
model_toycc=lm(Price~cc, data = toy)
summary(model_toycc)
model_toydoors=lm(Price~Doors, data = toy)
summary(model_toydoors)
model_toyccd=lm(Price~cc+Doors, data = toy)
summary(model_toyccd)
 stepAIC(model_toy)
library(car) 
 plot(model_toy)
influenceIndexPlot(model_toy) 
influencePlot(model_toy)
model_toy=lm(Price~Age_08_04+KM+HP+cc+Doors+Gears+Quarterly_Tax+Weight 
             , data = toy[c(-961 ,-222,-81),])
summary(model_toy)
pred=predict(model_toy, interval = "predict")
pred
